version: '3.9'

services:
  server:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - pgadmin
    networks:
      - botnet

  vue:
    container_name: vue
    build:
      context: client/
    ports:
      - "8080:8080"
    volumes:
      - ./api/app:/app
    depends_on:
      - server
    networks:
      - botnet

  db:
    container_name: pg_db
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
#    volumes:
#      - ./postgres_data:/var/lib/postgresql/data/
    networks:
      - botnet

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: noemail@noemail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - botnet

networks:
  botnet:
    driver: bridge
